### PR TITLE
Add CoreUI to magasin_web

### PR DESCRIPTION
**Pull request by bokay**

### CODE REVIEW

**Comment by bokay** [comment]
Note: 
We are using the coreui-pro version.
Hence, we won't use npm to grab the coreui module, but instead, we will do a copy of files from the zip bundle. This way, the swap from coreui to coreui-pro will be easier.

**Comment by nicholasjhenry** [comment]
If we download the latest update (see 1Password for link) the layout will be a lot closer:

`coreui-pro-bootstrap-admin-template-starter-2.1.0`

**Comment by bokay** [comment]
This PR can be closed, in favor of #71

**Comment by bokay** [comment]
@nicholasjhenry sorry for the confusion, this is the wrong PR to review. -> #71 
Closing this one.

**Pull request closed without merging**
